# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{torque-vpc-toolkit}
  s.version = "1.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dan Prince"]
  s.date = %q{2012-02-23}
  s.default_executable = %q{torque-vpc-toolkit}
  s.description = %q{Rake tasks to submit, and poll Torque jobs.}
  s.email = %q{dan.prince@rackspace.com}
  s.executables = ["torque-vpc-toolkit"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".rvmrc",
    "COPYING",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/torque-vpc-toolkit",
    "contrib/conf/jobs.json.example",
    "contrib/rake/Rakefile",
    "lib/http_util.rb",
    "lib/torque-vpc-toolkit.rb",
    "rake/torque_vpc_toolkit.rake"
  ]
  s.homepage = %q{http://github.com/dprince/torque_vpc_toolkit}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Rake tasks to submit Torque jobs.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rake>, [">= 0"])
      s.add_runtime_dependency(%q<chef-vpc-toolkit>, [">= 2.0"])
    else
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<chef-vpc-toolkit>, [">= 2.0"])
    end
  else
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<chef-vpc-toolkit>, [">= 2.0"])
  end
end

